name: google-docs-to-github
description: Export Google Docs to GitHub.
inputs:
  github_branch:
    description: GitHub branch name where files will be pushed.
    required: false
    default: main
  github_directory:
    description: GitHub directory path where files will be pushed.
    required: false
    default: google_docs
  github_token:
    description: GitHub access token to push files.
    required: false
  google_drive_folder_id:
    description: ID of the Google Drive folder to be exported.
    required: true
  google_drive_query:
    description: An optional where clause to filter the files from Google drive.
    required: false
runs:
  using: composite
  steps:
    - uses: mcleanra/google-docs-to-markdown@main
      with:
        google_drive_folder_id: ${{ inputs.google_drive_folder_id }}
        google_drive_query: ${{ inputs.google_drive_query }}
    - uses: peaceiris/actions-gh-pages@v3
      with:
        destination_dir: ${{ inputs.github_directory }}
        disable_nojekyll: true
        github_token: ${{ inputs.github_token || github.token }}
        publish_branch: ${{ inputs.github_branch }}
        publish_dir: output
branding:
  color: blue
  icon: download-cloud
